// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace BookStore.Data
{
    public partial class Book
    {
        public const string Codename = "book";
        public const string AuthorCodename = "author";
        public const string CategoryCodename = "category";
        public const string DescriptionCodename = "description";
        public const string NameCodename = "name";
        public const string ReleaseDateCodename = "release_date";

        public string Author { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}